### PR TITLE
Manually recreate a table if any column needs to add/remove constraint

### LINKED ISSUE #2: Throw exception if primary key tries to be altered
Altering constraints is not yet supported in duckdb. Right now, an alter request for primary key modification is silently ignored. Change it to throw an exception instead.

https://github.com/duckdb/duckdb/issues/57

### LINKED ISSUE #44: Alter table with constraints is not supported in DuckDB
Manually add/remove constraints? 

fivetran_log changed table structure, and now syncs are failing with `Parser Error: Adding columns with constraints not yet supported`.

### PR DESCRIPTION
**Pull request by elefeint**
DuckDB does not yet support ALTER TABLE with any constraints modifications (even DROP COLUMN fails if the column has a primary key).

This PR works around the limitation by renaming the original table, creating a new table with the correct structure, and copying all the old data from columns that were present in both the old table and the new table structure into it.

Fixes #44.
Fixes #2 in a better way (by making it work rather than throwing exception).
Fixes ECO-149

### CODE REVIEW

File: test/integration/test_server.cpp [hunk 1]
```diff
@@ -1177,3 +1177,293 @@ TEST_CASE("Test all types with create and describe table") {
...
+    request.mutable_table()->set_name(table_name);
+    auto col1 = request.mutable_table()->add_columns();
+    col1->set_name("id");
+    col1->set_type(::fivetran_sdk::DataType::STRING);
+    col1->set_primary_key(true);
+
+    auto col2 = request.mutable_table()->add_columns();
+    col2->set_name("name");
+    col2->set_type(::fivetran_sdk::DataType::STRING);
+    col2->set_primary_key(true);
```
Comment (hrl20) [inline test/integration/test_server.cpp:1228]: should this be false initially?

Comment (elefeint) [reply test/integration/test_server.cpp:1228]: no, it was "false" in create-table block above. This is turning an existing column that was previously NOT a primary key into a primary key.

Comment (hrl20) [reply test/integration/test_server.cpp:1228]: the test block below `// Alter Table to make an existing (unique valued) column into a primary key` 
has the comment `// turn existing column into a primary key`
```
    auto col2 = request.mutable_table()->add_columns();
    col2->set_name("name");
    col2->set_type(::fivetran_sdk::DataType::STRING);
    col2->set_primary_key(true); // turn existing column into a primary key
```
 so i thought this block should not set this column to a primary key.

Comment (elefeint) [reply test/integration/test_server.cpp:1258]: huh, you are right; I think I duplicated something somewhere

File: src/sql_generator.cpp [hunk 2]
```diff
@@ -219,48 +298,90 @@ void alter_table(duckdb::Connection &con, const table_def &table,
...
+      common_columns.emplace(col.name);
+    }
+
+    if (new_col_it == new_column_map.end()) {
+      deleted_columns.emplace(col.name);
+      if (col.primary_key) {
+        recreate_table = true;
+      }
+    } else if (new_col_it->second.type != col.type) {
+      alter_types.emplace(col.name);
```
Comment (hrl20) [inline src/sql_generator.cpp:352]: why can a change of type happen in place?

File: test/integration/test_server.cpp (hunk 1 above)
Comment (elefeint) [reply test/integration/test_server.cpp]: I switched it back to false, and refactored to make it a bit easier to read

File: src/sql_generator.cpp (hunk 2 above)
Comment (hrl20) [reply src/sql_generator.cpp:352]: or rather, why does this check come before the `new_col_it->second.primary_key != col.primary_key` check, and take precedence over change of primary key status

Comment (elefeint) [reply src/sql_generator.cpp:352]: if the types are compatible, it will work. If they are not, this should not be happening in the first place, and recreating a table won't really help
```
D create table a (col short);
D insert into a (col) values (1), (2), (3);
D select * from a;
┌───────┐
│  col  │
│ int16 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
D alter table a alter col type INT;
D select * from a;
┌───────┐
│  col  │
│ int32 │
├───────┤
│     1 │
│     2 │
│     3 │
└───────┘
```

Comment (elefeint) [reply src/sql_generator.cpp:352]: oh, that's a good point; I'll switch them

Comment (elefeint) [reply src/sql_generator.cpp]: done!

**Review by hrl20 — APPROVED** [review]
