### PR TITLE
Fix JSON handling by making it VARCHAR

### LINKED ISSUE #20: JSON data type is wrong
JSON should be either JSON or VARCHAR, not struct.

Struct requires defining the type at table creation time, while JSON does not come with structure.

### PR DESCRIPTION
**Pull request by elefeint**
It's a "good enough" solution -- when querying, the column value can always be cast to `::JSON`. 

The full solution requires building DuckDB differently, which is a bigger task and might lead to new build problems on the server, too. I filed a follow up issue #22 .

I updated some comments about type conversion while I was in that file.

For comparison, both [BigQuery](https://fivetran.com/docs/destinations/bigquery) and [Redshift](https://fivetran.com/docs/destinations/redshift) treat JSON as VARCHAR.

Fixes #20

### CODE REVIEW

**Review by guenp — APPROVED** [review]
This seems like a reasonable workaround to me, the only feedback I'd have is to add a note to the docs or code that it's a workaround with a link to issue #22

File: src/fivetran_duckdb_interop.cpp [hunk 1]
```diff
@@ -51,18 +47,20 @@ LogicalTypeId get_duckdb_type(const fivetran_sdk::DataType &fivetranType) {
...
     return LogicalTypeId::DECIMAL;
   case fivetran_sdk::BINARY:
-    return LogicalTypeId::BIT; // TBD: double check if correct
+    return LogicalTypeId::BIT;
   case fivetran_sdk::STRING:
     return LogicalTypeId::VARCHAR;
   case fivetran_sdk::JSON:
-    return LogicalTypeId::STRUCT;
+    return LogicalTypeId::
+        VARCHAR; // https://github.com/MotherDuck-Open-Source/motherduck-fivetran-connector/issues/22
```
Comment (guenp) [inline src/fivetran_duckdb_interop.cpp:63]: Ah, NVM - I see you already did that here. Disregard my previous comment
