### PR TITLE
fix: Change primary key syntax to work for a multi column primary key

### LINKED ISSUE #10: Create primary key as a composite
The syntax for creating a composite primary key is:
```
create table a3 (id int, id2 int, PRIMARY KEY (id, id2))
```

The current way does not work:
```
D create table a2 (id int primary key, id2 int primary key;
table "a2" has more than one primary key
```

### PR DESCRIPTION
**Pull request by elefeint**
Fixes #10

### CODE REVIEW

File: src/sql_generator.cpp [hunk 1]
```diff
@@ -78,20 +80,26 @@ void create_schema(duckdb::Connection &con, const std::string &db_name,
...
-      ddl << " PRIMARY KEY";
-    }
     ddl << ", "; // DuckDB allows trailing commas
   }
 
+  if (!columns_pk.empty()) {
+    ddl << "PRIMARY KEY (";
+    write_joined(
+        ddl, columns_pk,
+        [](const std::string &name, std::ostringstream &out) { out << name; });
```
Comment (nicku33) [inline src/sql_generator.cpp:99]: do we need quoting ?

Comment (elefeint) [reply src/sql_generator.cpp]: great catch; made the `write_joined` method always quote the column name (since it knows for sure this is a column name) and refactored the trivial "just print the quoted column name" lambda out into a constant.

**Review by nicku33 — APPROVED** [review]
